### ISSUE TITLE
3.x fails with fable

### ISSUE THREAD

**Issue by OnurGumus** [fsprojects/FSharp.Control.AsyncSeq#117]
### Description

When I use the library with fable I am getting the below error:
`
Module build failed (from ./node_modules/fable-loader/index.js):
Error: Could not find file '/home/onur/projects/infill2/.fable/FSharp.Control.AsyncSeq.3.0.1/AsyncSeq.fsi'.
    at /home/onur/projects/infill2/node_modules/fable-loader/index.js:98:22
`

The downgrading to 2.x solves the issue.

**Comment by davedawkins** [comment]
Also getting same error. The .fsi is in the git repository, was it missed from the pkg?

**Comment by dsyme** [comment]
I'm not sure, I know nothing about fable packaging but did accept a pr. Can you take a look?

**Comment by davedawkins** [comment]
I think you can ignore the Fable bit. It appears to be an issue with the NuGet pkg. I'm not sure how these are built, but if you're able to fix the NuGet pkg then you'll fix Fable too.
I may be able to research the nuget build procedure tomorrow.

**Comment by martinmoec** [comment]
I have also come across this issue. The reason is that the fable compiler will copy the contents of 
`<ItemGroup>
    <Content Include="*.fsproj; **\*.fs" PackagePath="fable\" />
  </ItemGroup>` into a .fable folder upon compiling. The copied .fsproj file includes `<Compile Include="AsyncSeq.fsi" />`, which is not copied by the Fable compiler, as only the .fsproj and .fs files are copied. 

Changing to `<Content Include="*.fsproj; **\*.fs; **\*.fsi;" PackagePath="fable\" />` should make it compatible with Fable.

Alternatively, you can navigate to `.fable/FSharp.Control.AsyncSeq.3.*` in your Fable project and remove `<Compile Include="AsyncSeq.fsi" />`. from the .fsproj file.

**Comment by njlr** [comment]
Would someone be able to push this fix (https://github.com/fsprojects/FSharp.Control.AsyncSeq/pull/118) to Nuget?

**Comment by wilsoncg** [comment]
done, v3.0.2 released
let me know if any further issues
